# Generated by Django 5.0.4 on 2025-08-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_userconversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconversation',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='userconversation',
            old_name='road',
            new_name='road_name',
        ),
    ]
