# Generated by Django 5.0.4 on 2025-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rename_comments_userconversation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconversation',
            name='step',
            field=models.CharField(default='start', max_length=20),
        ),
    ]
