# Generated by Django 5.0.4 on 2025-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_userconversation_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconversation',
            name='chat_id',
            field=models.CharField(max_length=50),
        ),
    ]
