# Generated by Django 5.0.4 on 2025-08-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_alter_userconversation_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadrating',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
