# Generated by Django 5.0.4 on 2025-08-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_roadrating_gps_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconversation',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
