# Generated by Django 5.0.4 on 2025-08-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_userconversation_gps_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconversation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='userconversation',
            name='gps_coordinates',
        ),
        migrations.RemoveField(
            model_name='userconversation',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userconversation',
            name='road_name',
        ),
    ]
