# Generated by Django 5.0.4 on 2025-08-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_remove_userconversation_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconversation',
            name='step',
        ),
    ]
