# Generated by Django 5.0.4 on 2025-09-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_teleuser_remove_userconversation_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconversation',
            name='fk_chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_chat_id', to='ratings.teleuser'),
        ),
    ]
