# Generated by Django 5.0.4 on 2025-09-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_alter_userconversation_fk_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadrating',
            name='road_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
