# Generated by Django 5.0.4 on 2025-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_alter_roadrating_road_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadrating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
