# Generated by Django 5.0.4 on 2025-09-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_alter_roadrating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconversation',
            name='state',
        ),
    ]
