# Generated by Django 5.0.4 on 2025-09-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_teleuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='otp_active',
            field=models.BooleanField(default=False),
        ),
    ]
