# Generated by Django 5.0.4 on 2025-09-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0016_teleuser_otp_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='road_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fk_road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ratings.roadrating')),
            ],
        ),
    ]
