# Generated by Django 5.0.4 on 2025-09-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0017_roadmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmedia',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('doc', 'Document')], default='photo', max_length=10),
        ),
        migrations.AlterField(
            model_name='roadmedia',
            name='file_url',
            field=models.URLField(),
        ),
    ]
